# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Documents and Settings\yanis\My Documents\LiClipse Workspace\PyGMI\PyGMI_files\Instruments_panels\Keithley2001.ui'
#
# Created: Wed Dec 20 13:46:25 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Panel(object):
    def setupUi(self, Panel):
        Panel.setObjectName("Panel")
        Panel.resize(634, 116)
        self.gridLayout = QtGui.QGridLayout(Panel)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtGui.QLabel(Panel)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(Panel)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.I_disp = QtGui.QLabel(Panel)
        self.I_disp.setMinimumSize(QtCore.QSize(109, 0))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.I_disp.setFont(font)
        self.I_disp.setAutoFillBackground(False)
        self.I_disp.setStyleSheet("background-color: rgb(0, 1, 0);\n"
"color: rgb(250, 28, 51);")
        self.I_disp.setFrameShape(QtGui.QFrame.WinPanel)
        self.I_disp.setFrameShadow(QtGui.QFrame.Sunken)
        self.I_disp.setScaledContents(False)
        self.I_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.I_disp.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.I_disp.setObjectName("I_disp")
        self.gridLayout.addWidget(self.I_disp, 1, 0, 1, 1)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(Panel)
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setMinimum(-1000000.0)
        self.doubleSpinBox.setMaximum(1000000.0)
        self.doubleSpinBox.setSingleStep(50.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 1, 1, 1, 1)
        self.monitor = QtGui.QCheckBox(Panel)
        self.monitor.setChecked(False)
        self.monitor.setObjectName("monitor")
        self.gridLayout.addWidget(self.monitor, 1, 4, 1, 1)
        self.V_disp = QtGui.QLabel(Panel)
        
        self.filter = QtGui.QCheckBox(Panel)
        self.filter.setObjectName("filter")
        self.gridLayout.addWidget(self.filter, 2,4,2,2)
        
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.V_disp.setFont(font)
        self.V_disp.setAutoFillBackground(False)
        self.V_disp.setStyleSheet("background-color: rgb(0, 1, 0);\n"
"color: rgb(250, 28, 51);")
        self.V_disp.setFrameShape(QtGui.QFrame.WinPanel)
        self.V_disp.setFrameShadow(QtGui.QFrame.Sunken)
        self.V_disp.setScaledContents(False)
        self.V_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.V_disp.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.V_disp.setObjectName("V_disp")
             
        self.gridLayout.addWidget(self.V_disp, 4, 0, 1, 1)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(Panel)
        self.doubleSpinBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_2.setDecimals(3)
        self.doubleSpinBox_2.setMinimum(-50.0)
        self.doubleSpinBox_2.setMaximum(50.0)
        self.doubleSpinBox_2.setSingleStep(1.0)
        self.doubleSpinBox_2.setProperty("value", 10.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout.addWidget(self.doubleSpinBox_2, 4, 1, 1, 1)
        self.measurementMode = QtGui.QComboBox(Panel)
        self.measurementMode.setObjectName("measurementMode")
        self.measurementMode.addItem("")
        self.measurementMode.addItem("")
        self.gridLayout.addWidget(self.measurementMode, 1, 3, 1, 1)
        self.label = QtGui.QLabel(Panel)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.refresh_rate = QtGui.QDoubleSpinBox(Panel)
        self.refresh_rate.setMinimumSize(QtCore.QSize(91, 0))
        self.refresh_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.refresh_rate.setDecimals(1)
        self.refresh_rate.setMaximum(9999999.0)
        self.refresh_rate.setSingleStep(0.5)
        self.refresh_rate.setProperty("value", 2.0)
        self.refresh_rate.setObjectName("refresh_rate")
        self.gridLayout.addWidget(self.refresh_rate, 4, 3, 1, 1)
        self.label_47 = QtGui.QLabel(Panel)
        self.label_47.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_47.setObjectName("label_47")
        self.gridLayout.addWidget(self.label_47, 2, 3, 1, 1)
        self.resetbutton = QtGui.QPushButton(Panel)
        self.resetbutton.setObjectName("resetbutton")
        self.gridLayout.addWidget(self.resetbutton, 4, 4, 1, 1)

        self.retranslateUi(Panel)
        QtCore.QObject.connect(self.monitor, QtCore.SIGNAL("clicked(bool)"), Panel.monitor)
        QtCore.QObject.connect(self.filter, QtCore.SIGNAL("clicked(bool)"), Panel.filter)
        QtCore.QObject.connect(self.refresh_rate, QtCore.SIGNAL("valueChanged(double)"), Panel.update_timer_timeout)
        QtCore.QObject.connect(self.doubleSpinBox, QtCore.SIGNAL("valueChanged(double)"), Panel.change_I)
        QtCore.QObject.connect(self.doubleSpinBox_2, QtCore.SIGNAL("valueChanged(double)"), Panel.change_V_comp)
        QtCore.QObject.connect(self.resetbutton, QtCore.SIGNAL("clicked()"), Panel.reset_inst)
        QtCore.QObject.connect(self.measurementMode, QtCore.SIGNAL("currentIndexChanged(int)"), Panel.change_measurement_mode)
        QtCore.QMetaObject.connectSlotsByName(Panel)

    def retranslateUi(self, Panel):
        Panel.setWindowTitle(QtGui.QApplication.translate("Panel", "Keithley 2001", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Panel", "Scaling options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Panel", "Measurement Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.I_disp.setText(QtGui.QApplication.translate("Panel", "-------- μA", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox.setSuffix(QtGui.QApplication.translate("Panel", " μA", None, QtGui.QApplication.UnicodeUTF8))
        self.monitor.setText(QtGui.QApplication.translate("Panel", "Monitor", None, QtGui.QApplication.UnicodeUTF8))
        self.filter.setText(QtGui.QApplication.translate("Panel", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.V_disp.setText(QtGui.QApplication.translate("Panel", "-------- V", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_2.setSuffix(QtGui.QApplication.translate("Panel", " V", None, QtGui.QApplication.UnicodeUTF8))
        self.measurementMode.setItemText(0, QtGui.QApplication.translate("Panel", "AC", None, QtGui.QApplication.UnicodeUTF8))
        self.measurementMode.setItemText(1, QtGui.QApplication.translate("Panel", "DC", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Panel", "Measurements", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh_rate.setSuffix(QtGui.QApplication.translate("Panel", " secs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("Panel", "Refresh rate", None, QtGui.QApplication.UnicodeUTF8))
        self.resetbutton.setText(QtGui.QApplication.translate("Panel", "Reset", None, QtGui.QApplication.UnicodeUTF8))

