# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Documents and Settings\yanis\My Documents\LiClipse Workspace\PyGMI\PyGMI_files\Instruments_panels\Keithley2001.ui'
#
# Created: Wed Jan 10 13:38:47 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Panel(object):
    def setupUi(self, Panel):
        Panel.setObjectName("Panel")
        Panel.resize(634, 116)
        self.gridLayout = QtGui.QGridLayout(Panel)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtGui.QLabel(Panel)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(Panel)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.I_disp = QtGui.QLabel(Panel)
        self.I_disp.setMinimumSize(QtCore.QSize(109, 0))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.I_disp.setFont(font)
        self.I_disp.setAutoFillBackground(False)
        self.I_disp.setStyleSheet("background-color: rgb(0, 1, 0);\n"
"color: rgb(250, 28, 51);")
        self.I_disp.setFrameShape(QtGui.QFrame.WinPanel)
        self.I_disp.setFrameShadow(QtGui.QFrame.Sunken)
        self.I_disp.setScaledContents(False)
        self.I_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.I_disp.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.I_disp.setObjectName("I_disp")
        self.gridLayout.addWidget(self.I_disp, 1, 0, 1, 1)
        self.monitor = QtGui.QCheckBox(Panel)
        self.monitor.setChecked(False)
        self.monitor.setObjectName("monitor")
        self.gridLayout.addWidget(self.monitor, 1, 4, 1, 1)
        self.V_disp = QtGui.QLabel(Panel)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.V_disp.setFont(font)
        self.V_disp.setAutoFillBackground(False)
        self.V_disp.setStyleSheet("background-color: rgb(0, 1, 0);\n"
"color: rgb(250, 28, 51);")
        self.V_disp.setFrameShape(QtGui.QFrame.WinPanel)
        self.V_disp.setFrameShadow(QtGui.QFrame.Sunken)
        self.V_disp.setScaledContents(False)
        self.V_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.V_disp.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.V_disp.setObjectName("V_disp")
        self.gridLayout.addWidget(self.V_disp, 4, 0, 1, 1)
        self.measurementMode = QtGui.QComboBox(Panel)
        self.measurementMode.setObjectName("measurementMode")
        self.measurementMode.addItem("")
        self.measurementMode.addItem("")
        self.gridLayout.addWidget(self.measurementMode, 1, 3, 1, 1)
        self.label = QtGui.QLabel(Panel)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.refresh_rate = QtGui.QDoubleSpinBox(Panel)
        self.refresh_rate.setMinimumSize(QtCore.QSize(91, 0))
        self.refresh_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.refresh_rate.setDecimals(1)
        self.refresh_rate.setMaximum(9999999.0)
        self.refresh_rate.setSingleStep(0.5)
        self.refresh_rate.setProperty("value", 2.0)
        self.refresh_rate.setObjectName("refresh_rate")
        self.gridLayout.addWidget(self.refresh_rate, 4, 3, 1, 1)
        self.label_47 = QtGui.QLabel(Panel)
        self.label_47.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_47.setObjectName("label_47")
        self.gridLayout.addWidget(self.label_47, 2, 3, 1, 1)
        self.resetbutton = QtGui.QPushButton(Panel)
        self.resetbutton.setObjectName("resetbutton")
        self.gridLayout.addWidget(self.resetbutton, 4, 4, 1, 1)
        self.vRange = QtGui.QComboBox(Panel)
        self.vRange.setObjectName("vRange")
        self.vRange.addItem("")
        self.vRange.addItem("")
        self.vRange.addItem("")
        self.vRange.addItem("")
        self.vRange.addItem("")
        self.vRange.addItem("")
        self.vRange.addItem("")
        self.gridLayout.addWidget(self.vRange, 4, 1, 1, 1)
        self.iRange = QtGui.QComboBox(Panel)
        self.iRange.setObjectName("iRange")
        self.iRange.addItem("")
        self.iRange.addItem("")
        self.iRange.addItem("")
        self.iRange.addItem("")
        self.iRange.addItem("")
        self.iRange.addItem("")
        self.iRange.addItem("")
        self.gridLayout.addWidget(self.iRange, 1, 1, 1, 1)
        self.filter = QtGui.QCheckBox(Panel)
        self.filter.setObjectName("filter")
        self.gridLayout.addWidget(self.filter, 2, 4, 1, 1)

        self.retranslateUi(Panel)
        QtCore.QObject.connect(self.monitor, QtCore.SIGNAL("clicked(bool)"), Panel.monitor)
        QtCore.QObject.connect(self.refresh_rate, QtCore.SIGNAL("valueChanged(double)"), Panel.update_timer_timeout)
        QtCore.QObject.connect(self.resetbutton, QtCore.SIGNAL("clicked()"), Panel.reset_inst)
        QtCore.QObject.connect(self.vRange, QtCore.SIGNAL("activated(int)"), Panel.change_v_range)
        QtCore.QObject.connect(self.iRange, QtCore.SIGNAL("activated(int)"), Panel.change_i_range)
        QtCore.QObject.connect(self.filter, QtCore.SIGNAL("clicked(bool)"), Panel.filter)
        QtCore.QMetaObject.connectSlotsByName(Panel)

    def retranslateUi(self, Panel):
        Panel.setWindowTitle(QtGui.QApplication.translate("Panel", "Keithley 2001", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Panel", "Scaling options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Panel", "Measurement Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.I_disp.setText(QtGui.QApplication.translate("Panel", "-------- A", None, QtGui.QApplication.UnicodeUTF8))
        self.monitor.setText(QtGui.QApplication.translate("Panel", "Monitor", None, QtGui.QApplication.UnicodeUTF8))
        self.V_disp.setText(QtGui.QApplication.translate("Panel", "-------- V", None, QtGui.QApplication.UnicodeUTF8))
        self.measurementMode.setItemText(0, QtGui.QApplication.translate("Panel", "AC", None, QtGui.QApplication.UnicodeUTF8))
        self.measurementMode.setItemText(1, QtGui.QApplication.translate("Panel", "DC", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Panel", "Measurements", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh_rate.setSuffix(QtGui.QApplication.translate("Panel", " secs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("Panel", "Refresh rate", None, QtGui.QApplication.UnicodeUTF8))
        self.resetbutton.setText(QtGui.QApplication.translate("Panel", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.vRange.setItemText(0, QtGui.QApplication.translate("Panel", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.vRange.setItemText(1, QtGui.QApplication.translate("Panel", "AUTO", None, QtGui.QApplication.UnicodeUTF8))
        self.vRange.setItemText(2, QtGui.QApplication.translate("Panel", "200mV", None, QtGui.QApplication.UnicodeUTF8))
        self.vRange.setItemText(3, QtGui.QApplication.translate("Panel", "2V", None, QtGui.QApplication.UnicodeUTF8))
        self.vRange.setItemText(4, QtGui.QApplication.translate("Panel", "20V", None, QtGui.QApplication.UnicodeUTF8))
        self.vRange.setItemText(5, QtGui.QApplication.translate("Panel", "200V", None, QtGui.QApplication.UnicodeUTF8))
        self.vRange.setItemText(6, QtGui.QApplication.translate("Panel", "750V", None, QtGui.QApplication.UnicodeUTF8))
        self.iRange.setItemText(0, QtGui.QApplication.translate("Panel", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.iRange.setItemText(1, QtGui.QApplication.translate("Panel", "AUTO", None, QtGui.QApplication.UnicodeUTF8))
        self.iRange.setItemText(2, QtGui.QApplication.translate("Panel", "200μΑ", None, QtGui.QApplication.UnicodeUTF8))
        self.iRange.setItemText(3, QtGui.QApplication.translate("Panel", "2mA", None, QtGui.QApplication.UnicodeUTF8))
        self.iRange.setItemText(4, QtGui.QApplication.translate("Panel", "20mA", None, QtGui.QApplication.UnicodeUTF8))
        self.iRange.setItemText(5, QtGui.QApplication.translate("Panel", "200mA", None, QtGui.QApplication.UnicodeUTF8))
        self.iRange.setItemText(6, QtGui.QApplication.translate("Panel", "2A", None, QtGui.QApplication.UnicodeUTF8))
        self.filter.setText(QtGui.QApplication.translate("Panel", "Filter", None, QtGui.QApplication.UnicodeUTF8))

